### ISSUE TITLE
Add mypy type checking

### ISSUE THREAD

**Issue by atolopko-czi** [chanzuckerberg/single-cell#366]
[Proposal for gradual mypy adoption](https://docs.google.com/document/d/1a3FULtraY9928HLBa3a_V784dVXs7izTJikqdm0XCK0/edit)

This epic will encompasses the work to complete the transition to use of the `mypy` type checking tool  ([docs](https://mypy.readthedocs.io/en/stable/index.html)) across our Python code bases.

Note: we only intend to require new code written to be type safe. Migrating existing code to be type safe is out of scope.

In Explorer, Portal, and Curation repos, we'll want to first turn on mypy for one module in the repo and verify everything is working as expected. Mechanically, this will entail:
* Add `mypy` to requirements.txt, along with any relevant 3rd-party [type checking "stubs"](https://github.com/python/typeshed/tree/main/stubs) that may be useful in each repo. 
* Add `[tool.mypy]` config section to `pyproject.toml` (missing in Curation repo, so use `mypy.ini` instead). [Example](https://github.com/chanzuckerberg/soma-scratch/blob/main/pyproject.toml#L9-L14). [Docs](https://mypy.readthedocs.io/en/stable/config_file.html).
* Run the script to annotate each offending line in the module with “type: ignore” which will instruct mypy to ignore that line, and commit the code from that.
* Add `mypy` target to `Makefile` that invokes `mypy` ([example](https://github.com/chanzuckerberg/soma-scratch/blob/main/.github/workflows/formatting.yml#L32)), similar to `fmt` and `lint` targets. 
* For each repo, choose one small package or module that you will update to be type checked by `mypy`, in order to kickstart our type checking enforcement effort. This will serve as an example and as an initial test that mypy invocation is working correctly. Add package or module to `pyproject.toml` config section, under [packages](https://mypy.readthedocs.io/en/stable/config_file.html#confval-packages) or [modules](https://mypy.readthedocs.io/en/stable/config_file.html#confval-modules) param, respectively, to enforce it is type checked.
* Test `make mypy`, iterating on type checking fixes as needed .
* Add `make mypy` call to GHA `lint` jobs.
* Test GHA `lint` job succeeds on push.
* Document in repo's README file, similar to `fmt` and `lint` Make targets usage.

Discuss among the team when in the calendar year it will be least disruptive to turn on mypy for all repos. Mechanically, this change for all repos (Explorer, Portal and Curation) will involve:
* Run the script across the entire repo to annotate each offending line with “type: ignore” which will instruct mypy to ignore that line, and commit the code from that.
* Update `pyproject.toml` to look at the entire repo instead of just one module, by removing the `packages = [...]` line
* Add a pre-commit hook to run on all new files in the repo
```
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.0
    hooks:
      - id: mypy
        stages: [ commit ]
        args: ["--config-file=pyproject.toml"]
        additional_dependencies:
          - types-requests
          - types-setuptools
          - typing_extensions
          - types-PyYAML
```
